# ---------------------------------------------------------------------------
# chat.R — Core chat logic using the ellmer package to communicate with Claude
# ---------------------------------------------------------------------------

library(ellmer)

#' Build the system prompt that instructs Claude how to behave.
#'
#' The prompt tells Claude to act as a SQL assistant: convert natural language
#' questions into read-only SQL, explain the query, and suggest a visualization.
#'
#' @param db_schema Character string describing the database schema (tables,
#'   columns, types). Generated by `get_db_schema()` in database.R.
#' @return A single character string containing the full system prompt.
get_system_prompt <- function(db_schema) {
  paste0(
    "You are a SQL assistant that converts natural language questions into SQL queries.\n\n",
    "## Rules\n",
    "1. ONLY generate SELECT queries. Never generate INSERT, UPDATE, DELETE, DROP, ALTER, ",
    "CREATE, or any other data-modification statement.\n",
    "2. Write clear, well-formatted SQL.\n",
    "3. Use the database schema provided below to ensure your queries reference valid ",
    "tables and columns.\n",
    "4. If the user's question is ambiguous, make reasonable assumptions and explain them.\n",
    "5. If the question cannot be answered with the available schema, say so clearly.\n",
    "6. Always provide a brief plain-English explanation of what the query does.\n",
    "7. Suggest an appropriate visualization type for the results (e.g., bar chart, ",
    "line chart, scatter plot, table, pie chart, histogram). Pick the type that best ",
    "fits the shape and meaning of the data.\n\n",
    "## Database Schema\n",
    "```\n",
    db_schema, "\n",
    "```\n\n",
    "Respond with structured output containing exactly three fields:\n",
    "- sql_query: the SQL SELECT query\n",
    "- explanation: a brief plain-English explanation of the query\n",
    "- suggested_visualization: the recommended chart type for the results\n"
  )
}


#' Define the structured output type for the LLM response.
#'
#' Uses ellmer's type system to ensure Claude returns a well-typed object with
#' three fields: sql_query, explanation, and suggested_visualization.
#'
#' @return An ellmer type_object specification.
get_response_type <- function() {
  type_object(
    sql_query = type_string("The SQL SELECT query that answers the user's question"),
    explanation = type_string("A brief plain-English explanation of the query"),
    suggested_visualization = type_string(
      "The recommended visualization type (e.g., bar_chart, line_chart, scatter_plot, table, pie_chart, histogram)"
    )
  )
}


#' Create a new chat session backed by Claude via the ellmer package.
#'
#' Each session holds its own conversation history so multi-turn interactions
#' work correctly.
#'
#' @param db_schema Character string with the database schema.
#' @param model The Claude model identifier. Defaults to the CLAUDE_MODEL env
#'   var, falling back to "claude-sonnet-4-20250514".
#' @return An ellmer Chat object ready to accept user messages.
create_chat_session <- function(db_schema,
                                model = Sys.getenv("CLAUDE_MODEL",
                                                   "claude-sonnet-4-20250514")) {
  # Validate that the API key is available
  api_key <- Sys.getenv("ANTHROPIC_API_KEY", "")
  if (api_key == "") {
    stop("ANTHROPIC_API_KEY environment variable is not set. ",
         "Please set it before starting the API.")
  }

  system_prompt <- get_system_prompt(db_schema)

  # Create the ellmer chat instance targeting Anthropic / Claude.
  # ellmer reads ANTHROPIC_API_KEY from the environment automatically.
  chat <- chat_anthropic(
    model = model,
    system_prompt = system_prompt
  )

  chat
}


#' Send a user message to an existing chat session and extract structured data.
#'
#' @param chat An ellmer Chat object (from `create_chat_session()`).
#' @param user_message The natural language question from the user.
#' @return A named list with `sql_query`, `explanation`, and
#'   `suggested_visualization`.
send_chat_message <- function(chat, user_message) {
  response_type <- get_response_type()

  # Use chat_structured for structured output — this tells Claude to respond
  # according to the type specification and parses the result automatically.
  result <- chat$chat_structured(user_message, type = response_type)

  result
}
